
server:
  port:
    8191

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VladimirPoddubchak/config-server
          search-paths:
            - 'service-config/*service'
